# Generated by Django 4.0.1 on 2022-06-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Usertype',
            field=models.SlugField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('addedAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added at')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_student', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
        ),
    ]
