# Generated by Django 4.0.1 on 2022-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_parent_teacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Usertype',
            field=models.SlugField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
