# Generated by Django 4.0.1 on 2022-06-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
