# Generated by Django 4.0.1 on 2022-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_teacher_teacher_alter_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
