# Generated by Django 4.0.1 on 2022-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_teacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
