# Generated by Django 4.0.1 on 2022-01-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errorlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.SlugField(blank=True, choices=[('na', 'N/a'), ('core', 'Core')], default='na', max_length=20, null=True, verbose_name='app')),
                ('page_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Page')),
                ('errortype', models.SlugField(blank=True, choices=[('na', 'N/a'), ('calc', 'Calculation'), ('read', 'Read'), ('post', 'Post')], default='na', null=True, verbose_name='type')),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.SlugField(choices=[('new', 'New'), ('fixed', ' Fixed'), ('onreview', 'On Review'), ('identified', 'Identified'), ('onprocess', 'Onprocess')], default='new', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Info')),
                ('key1', models.CharField(max_length=128, verbose_name='KEY1')),
                ('key2', models.CharField(blank=True, max_length=128, null=True, verbose_name='KEY2')),
                ('key3', models.CharField(blank=True, max_length=128, null=True, verbose_name='KEY3')),
                ('template', models.CharField(blank=True, max_length=256, null=True, verbose_name='Template')),
                ('config', models.CharField(blank=True, max_length=128, null=True, verbose_name='Config')),
                ('sender', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sender')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('isactive', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
