# Generated by Django 4.0.1 on 2022-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Info'),
        ),
    ]
