# Generated by Django 4.0.1 on 2022-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_errorlog_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=64, verbose_name='Feedback')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='Subject')),
                ('exam', models.CharField(blank=True, max_length=64, null=True, verbose_name='Exam')),
                ('mark', models.CharField(blank=True, max_length=14, null=True, verbose_name='Marks')),
                ('total', models.CharField(max_length=64, verbose_name='Total')),
                ('isactive', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Errorlog',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
