# Generated by Django 4.0.1 on 2022-06-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback_marks_delete_errorlog_delete_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='exam',
        ),
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.CharField(default=0, max_length=14, verbose_name='Marks'),
        ),
    ]
