# Generated by Django 4.0.1 on 2022-06-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_marks_exam_alter_marks_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
